export const SAVE_USER = "SAVE_USER";
export const LOG_OUT = "LOG_OUT";
export const SAVE_COURSES_OF_CURRENT_USER = "SAVE_COURSES_OF_CURRENT_USER";
export const SAVE_ALL_TEACHERS = "SAVE_ALL_TEACHERS";
export const UPDATE_USER="UPDATE_USER";
export const SAVE_CURRENT_STATUS="SAVE_CURRENT_STATUS";